services:
  app:
    image: snipe/snipe-it:v7.1.14
    restart: unless-stopped
    container_name: zsit-rsc-t1-snipeit
    volumes:
      - /opt/containers/zsit-rsc-t1-snipeit/snipeit:/var/lib/snipeit
    #ports:
    #  - "3128:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - snipe-internal
    environment:
      - APP_VERSION=v7.1.14
      - APP_PORT=80
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - APP_URL=http://localhost
      - APP_TIMEZONE='CET'
      - APP_LOCALE=en-US
      - MAX_RESULTS=500
      - PRIVATE_FILESYSTEM_DISK=local
      - PUBLIC_FILESYSTEM_DISK=local_public
      - DB_CONNECTION=mysql
      - DB_HOST=snipe_db
      - DB_PORT='3306'
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_PREFIX=null
      - DB_DUMP_PATH='/usr/bin'
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
      - MAIL_MAILER=smtp
      - MAIL_DRIVER=smtp
      - MAIL_HOST=10.21.25.3
      - MAIL_PORT=25
      - MAIL_USERNAME=schul-it@kreis-tuebingen.de
      - MAIL_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - MAIL_TLS_VERIFY_PEER=false
      - MAIL_FROM_ADDR=schul-it@application.kreis-tuebingen.de
      - MAIL_FROM_NAME='Schul-IT'
      - MAIL_REPLYTO_ADDR=schul-it@kreis-tuebingen.de
      - MAIL_REPLYTO_NAME='Schul-IT'
      - MAIL_AUTO_EMBED=false
      - MAIL_AUTO_EMBED_METHOD=base64
      - ALLOW_BACKUP_DELETE=false
      - ALLOW_DATA_PURGE=false
      - IMAGE_LIB=gd
      - BACKUP_ENV=true
      - SESSION_LIFETIME=12000
      - EXPIRE_ON_CLOSE=false
      - ENCRYPT=false
      - COOKIE_NAME=snipeit_session
      - COOKIE_DOMAIN=null
      - SECURE_COOKIES=false
      - API_TOKEN_EXPIRATION_YEARS=40
      - APP_TRUSTED_PROXIES=10.0.0.0/8,172.0.0.0/8,192.168.0.0/12
      - ALLOW_IFRAMING=false
      - REFERRER_POLICY=same-origin
      - ENABLE_CSP=false
      - CORS_ALLOWED_ORIGINS=null
      - ENABLE_HSTS=false
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - CACHE_PREFIX=snipeit
      - REDIS_HOST=snipe_redis
      - REDIS_PORT=6379
      - LOGIN_MAX_ATTEMPTS=2
      - LOGIN_LOCKOUT_DURATION=60
      - RESET_PASSWORD_LINK_EXPIRES=900
      - LOG_CHANNEL=stderr
      - LOG_MAX_DAYS=10
      - APP_LOCKED=false
      - APP_CIPHER=AES-256-CBC
      - APP_FORCE_TLS=false
      - GOOGLE_MAPS_API=
      - LDAP_MEM_LIM=500M
      - LDAP_TIME_LIM=600

  db:
    image: mariadb:11.5.2
    container_name: snipe_db
    restart: unless-stopped
    volumes:
      - /opt/containers/zsit-rsc-t1-snipeit/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - snipe-internal
  
  redis:
    image: redis
    restart: always
    container_name: snipe_redis
    networks:
      - snipe-internal
      
      
networks:
  snipe-internal:
