---
- hosts: 192.168.0.250
  become: yes
  tasks:
    - name: install update && upgrade
      shell: |
        wg-quick down wg0
        apt update && apt upgrade -y && apt-get autoremove
        echo "Update fertig"
        wg-quick up wg0
